-- PlanWise async task infrastructure schema additions
-- Create new tables without modifying existing production exports.

CREATE TABLE IF NOT EXISTS `planwise_task_queue` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `task_id` VARCHAR(64) NOT NULL,
  `user_id` INT(11) DEFAULT NULL,
  `report_id` VARCHAR(64) DEFAULT NULL,
  `task_type` VARCHAR(50) NOT NULL,
  `status` ENUM('pending','processing','completed','failed') DEFAULT 'pending',
  `priority` INT(11) DEFAULT 5,
  `payload` JSON,
  `result` JSON,
  `error_message` TEXT,
  `retry_count` INT(11) DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `started_at` TIMESTAMP NULL,
  `completed_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_task_id` (`task_id`),
  KEY `idx_status_priority` (`status`, `priority`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `planwise_reports_v2` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `report_id` VARCHAR(64) NOT NULL,
  `user_id` INT(11) DEFAULT NULL,
  `task_id` VARCHAR(64) DEFAULT NULL,
  `custom_id` VARCHAR(50) DEFAULT NULL,
  `title` VARCHAR(255) NOT NULL,
  `business_idea` TEXT NOT NULL,
  `industry` VARCHAR(100) DEFAULT NULL,
  `target_market` VARCHAR(100) DEFAULT NULL,
  `analysis_depth` ENUM('basic','standard','deep') DEFAULT 'standard',
  `status` ENUM('draft','analyzing','completed','failed') DEFAULT 'draft',
  `visibility` ENUM('private','public','shared') DEFAULT 'private',
  `share_token` VARCHAR(64) DEFAULT NULL,
  `total_words` INT(11) DEFAULT 0,
  `ai_tokens_used` INT(11) DEFAULT 0,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `completed_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_report_id` (`report_id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `planwise_report_steps` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `step_id` VARCHAR(64) NOT NULL,
  `report_id` VARCHAR(64) NOT NULL,
  `step_number` INT(11) NOT NULL,
  `step_name` VARCHAR(50) NOT NULL,
  `step_title` VARCHAR(100) NOT NULL,
  `task_id` VARCHAR(64) DEFAULT NULL,
  `status` ENUM('pending','processing','completed','failed','skipped') DEFAULT 'pending',
  `ai_model` VARCHAR(50) DEFAULT NULL,
  `prompt_template` TEXT,
  `ai_response` JSON,
  `formatted_content` MEDIUMTEXT,
  `word_count` INT(11) DEFAULT 0,
  `tokens_used` INT(11) DEFAULT 0,
  `processing_time` INT(11) DEFAULT 0,
  `retry_count` INT(11) DEFAULT 0,
  `error_message` TEXT,
  `error_code` VARCHAR(50) DEFAULT NULL,
  `metadata` JSON,
  `started_at` TIMESTAMP NULL,
  `completed_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_step_id` (`step_id`),
  UNIQUE KEY `uk_report_step` (`report_id`, `step_number`),
  KEY `idx_report_id` (`report_id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_status` (`status`),
  KEY `idx_step_name` (`step_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `planwise_user_quotas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `custom_id` VARCHAR(50) DEFAULT NULL,
  `category_group` VARCHAR(50) DEFAULT 'standard',
  `total_reports` INT(11) DEFAULT 10,
  `used_reports` INT(11) DEFAULT 0,
  `total_tokens` INT(11) DEFAULT 1000000,
  `used_tokens` INT(11) DEFAULT 0,
  `reset_date` DATE DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_id` (`user_id`),
  KEY `idx_custom_id` (`custom_id`),
  KEY `idx_category_group` (`category_group`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
